
// CART REDUCER
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const INCREMENT_ITEM = 'INCREMENT_ITEM';
export const DECREMENT_ITEM = 'DECREMENT_ITEM';


// FILTER REDUCER
export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
export const RESET_FILTER = 'RESET_FILTER';
export const FILTER_ITEM_BY_NAMES = 'FILTER_BY_NAMES';
export const CHANGE_SORTING_SEQ = 'CHANGE_SORTING_SEQ';


export const ProductActionTypes = {

}
